definitions:
  environment_versions: &env_versions
    xcode: 14.1
    vars:
      XCODE_PROJECT: "CountriesSwiftUI.xcodeproj"
      XCODE_iOS_SCHEME: "CountriesSwiftUI"
  artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Test/**/*.xcresult
  scripts:
    - &run_ios_tests
      name: Run iOS UI and Unit tests
      script: xcodebuild build -project "$XCODE_PROJECT" -scheme "$XCODE_iOS_SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.1' test 
workflows:
  ios-mac-pro-workflow:
    name: iOS Mac Pro Workflow
    instance_type: mac_pro
    environment:
      <<: *env_versions
    scripts:
      - *run_ios_tests
    
  ios-m1-mac-mini-workflow:
    name: iOS M1 Mac Mini Workflow
    instance_type: mac_mini_m1
    environment:
      <<: *env_versions
    scripts:
      - *run_ios_tests
